spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: example_route
          uri: http://httpbin.org:80
          predicates:
            - Path=/get
        - id: postman_echo_route
          uri: https://postman-echo.com
          predicates:
            - Path=/postman-echo/get
          filters:
            - StripPrefix=1
        - id: reqres_route
          uri: https://reqres.in
          predicates:
            - Path=/reqres/users/{id}
          filters:
            - StripPrefix=1
            - RewritePath=/users/(?<id>.*), /api/users/${id}
  redis:
    enabled: false

server:
  port: 8080

management:
  health:
    redis:
      enabled: false
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: gateway-service
    export:
      prometheus:
        enabled: true
  security:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG

