global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080", "host.docker.internal:8082"]
        labels:
          application: "gateway-service"

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          application: "auth-service"
